name: Build

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Build_$(date +"%Y%m%d_%H%M")"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build
        run: python ./build.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ./build/releases/*.aseprite-extension
